app = "imperio"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true  # Esto apaga la app si no hay trafico
  auto_start_machines = true # La prende cuando alguien entra
  min_machines_running = 0   # Importante: que llegue a cero
  processes = ["app"]
