service: imperio
image: aldoax2/imperio
secrets_path: .kamal/secrets

servers:
  web:
    - 138.197.117.170

ssh:
  user: root

proxy:
  app_port: 3000
  ssl: false
  healthcheck:
    path: /up
    interval: 3
    timeout: 10
  response_timeout: 30

registry:
  username: aldoax2
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    RAILS_ENV: production
    PORT: 3000
    RAILS_LOG_LEVEL: info
    RAILS_MAX_THREADS: 5
    FORCE_SSL: "false"
    RAILS_ASSUME_SSL: "false"
  secret:
    - DATABASE_URL
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
    - S3_REGION
    - S3_BUCKET

asset_path: /rails/public/assets
